### ISSUE TITLE
error on version 2.8

### ISSUE THREAD

**Issue by rehananis** [CIRAIG/OpenIO-Canada#27]
Hi Maxime, I am running openIO ver 2.8 on 2019 data but I am getting the following error. 

2024-03-15 11:23:52,211 - openIO-Canada - INFO - Reading all the Excel files...
2024-03-15 11:24:10,311 - openIO-Canada - INFO - Formatting the Supply and Use tables...
2024-03-15 11:25:10,107 - openIO-Canada - INFO - Modifying names of duplicated sectors...
2024-03-15 11:25:10,261 - openIO-Canada - INFO - Organizing final demand sectors...
2024-03-15 11:25:11,000 - openIO-Canada - INFO - Removing IOIC codes from index...
2024-03-15 11:25:11,572 - openIO-Canada - INFO - Balancing inter-provincial trade...
2024-03-15 11:26:53,205 - openIO-Canada - INFO - Pre-treatment of international trade data...
2024-03-15 11:27:23,262 - openIO-Canada - INFO - Linking international trade data to openIO-Canada...
2024-03-15 11:29:07,863 - openIO-Canada - INFO - Building the symmetric tables...
2024-03-15 11:29:16,658 - openIO-Canada - INFO - Linking openIO-Canada to Exiobase...
2024-03-15 11:39:16,996 - openIO-Canada - INFO - Extracting and formatting environmental data from the NPRI file...
2024-03-15 11:39:19,180 - openIO-Canada - INFO - Matching emission data from NPRI to IOT sectors...
2024-03-15 11:39:20,961 - openIO-Canada - INFO - Matching GHG accounts to IOT sectors...
2024-03-15 11:39:26,570 - openIO-Canada - INFO - Matching water accounts to IOT sectors...
2024-03-15 11:39:33,883 - openIO-Canada - INFO - Matching energy accounts to IOT sectors...
2024-03-15 11:39:37,861 - openIO-Canada - INFO - Matching mineral extraction data to IOT sectors...
2024-03-15 11:39:38,762 - openIO-Canada - INFO - Creating the characterization matrix...
2024-03-15 11:46:21,747 - openIO-Canada - INFO - Refining the GHG emissions for the agriculture sector...
2024-03-15 11:46:21,932 - openIO-Canada - INFO - Cleaning province and country names...
2024-03-15 11:46:22,044 - openIO-Canada - INFO - Refining the GHG emissions for the meat sector...
2024-03-15 11:46:29,461 - openIO-Canada - INFO - Adding HFP and PFC flows...
2024-03-15 11:47:15,846 - openIO-Canada - INFO - Refining water consumption of livestock and crops...
2024-03-15 11:47:23,616 - openIO-Canada - INFO - Adding plastic waste flows...
Traceback (most recent call last):
  File "C:\Users\ranis\AppData\Roaming\Python\Python39\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'CA-AB'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "J:\F_Drive\CIRAIG_Training\OpenIOCanada\ARA_EEMARIO.py", line 20, in <module>
    tables = openIO.IOTables(folder_path,exiobase_folder,endogenizing_capitals=False, aggregated_ghgs=True)
  File "J:\F_Drive\CIRAIG_Training\OpenIOCanada\openIO.py", line 240, in __init__
    self.add_plastic_emissions()
  File "J:\F_Drive\CIRAIG_Training\OpenIOCanada\openIO.py", line 2614, in add_plastic_emissions
    self.K.loc(axis=0)[:, product].loc[:, 'CA-' + province].sum(1))
  File "C:\Users\ranis\AppData\Roaming\Python\Python39\site-packages\pandas\core\indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\ranis\AppData\Roaming\Python\Python39\site-packages\pandas\core\indexing.py", line 1100, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\ranis\AppData\Roaming\Python\Python39\site-packages\pandas\core\indexing.py", line 822, in _getitem_lowerdim
    return self._getitem_nested_tuple(tup)
  File "C:\Users\ranis\AppData\Roaming\Python\Python39\site-packages\pandas\core\indexing.py", line 906, in _getitem_nested_tuple
    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)
  File "C:\Users\ranis\AppData\Roaming\Python\Python39\site-packages\pandas\core\indexing.py", line 1164, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\Users\ranis\AppData\Roaming\Python\Python39\site-packages\pandas\core\indexing.py", line 1113, in _get_label
    return self.obj.xs(label, axis=axis)
  File "C:\Users\ranis\AppData\Roaming\Python\Python39\site-packages\pandas\core\generic.py", line 3761, in xs
    return self[key]
  File "C:\Users\ranis\AppData\Roaming\Python\Python39\site-packages\pandas\core\frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\ranis\AppData\Roaming\Python\Python39\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'CA-AB'
>>>

**Comment by MaximeAgez** [comment]
Should be fixed in the latest commit.

**Comment by rehananis** [comment]
thanks
